### ISSUE TITLE
URL of PDF not visible in omnibox

### ISSUE THREAD

**Issue by Rob--W** [operasoftware/pdf.js#11]
Because of https://github.com/mozilla/pdf.js/pull/3751 and the fact that Opera hides the URL on `chrome-extension://` schemes, the URL of the PDF will be invisible when you pull the latest PDF version from Mozilla's master branch.

This bug originally appeared in Chrome, but it was fixed almost a half year ago (http://crbug.com/72021). Apparently, the patch has never landed in Opera though.

PS. To make it clear: This bug does not exists at the moment, but it will when you pull the latest code from Mozilla.

**Comment by slawkacz** [comment]
Could we just use history.push workaround?

**Comment by Rob--W** [comment]
`history.pushState` and `history.replaceState` cannot rewrite the scheme, host, or port. That would be a huge security issue.
That having said, the issue is that the omnibox is empty, i.e. it doesn't show an URL _at all_:

![opera](https://f.cloud.github.com/assets/1365071/1359408/dc28cb36-37dc-11e3-8f47-fbfac640c4fd.png)

**Comment by Rob--W** [comment]
Solved by #4006. I will close the issue once Opera updates their PDF.js release.
