### ISSUE TITLE
Cannot be used to view locally-stored PDF files

### ISSUE THREAD

**Issue by MaxBarraclough** [operasoftware/pdf.js#12]
If I download a .PDF file to disk, then drag-and-drop it into Opera, then PDF.js is not used. Instead, Opera 'downloads' the file to my Downloads folder.

**Comment by Rob--W** [comment]
Did you allow access to file URLs? Visit the extensions page (Ctrl + Shift + E) and make sure that the following checkbox is checked:

![Allow access to file URLs](https://f.cloud.github.com/assets/1365071/1360486/c3e0c140-37f6-11e3-89fa-a0bb8750dfcb.png)

**Comment by MaxBarraclough** [comment]
I didn't notice that tick-box - that's fixed it.

It's unintuitive that the default is for this to be disabled. Is this up to the plugin, or the Opera browser itself?

**Comment by Rob--W** [comment]
It's up to the browser. Chrome has the same limitations.
