### ISSUE TITLE
Feature suggestion: save pdf with Ctrl+S/Cmd+S shorcut

### ISSUE THREAD

**Issue by zmwangx** [operasoftware/pdf.js#18]
This is an Opera specific issue. I'm using PDF Viewer extension 0.8.997 on Opera 19.0.1326.63, OS X 10.9.1. Up to this release, **pdf files cannot be saved by using the Cmd+S shortcut.** Cmd+S brings up a html save dialogue, which is not useful at all. The  shortcut is **already implemented in Firefox** (currently PDF Viewer 0.8.649 on Firefox 27.0.1).

I apologize if this is not the right place to suggest a feature. The guidelines for contributing points to the Mozilla dev mailing list, which I suppose is the wrong place for Opera specific features.

**Comment by da2x** [comment]
This should work on Mac starting with Opera 21. You can test it now if you would like to from http://www.opera.com/developer

**Comment by zmwangx** [comment]
Sorry, but with PDF Viewer 0.8.997 (from addons.opera.com) on Opera Developer 21.0.1419.0, I still get the following html save dialogue rather than a pdf one (see screenshot below). I have checked "Allow access to file URLs," in case that is relevant. Am I missing something, e.g., a developer build of the plugin? Thanks.
![screen shot 2014-02-24 at 3 31 53 pm](https://f.cloud.github.com/assets/4149852/2252616/dfa52496-9dab-11e3-81a9-df9c0cea263c.png)

**Comment by Rob--W** [comment]
At the next update, this bug will be fixed.

**Comment by zmwangx** [comment]
Got it, thanks.
