### ISSUE TITLE
PDF viewer doesn't work  - no error message.....

### ISSUE THREAD

**Issue by 5953lc** [operasoftware/pdf.js#3]
What is the minimum PDF file version that should be used with the PDF.js extension?
v1.2 or v1.4 ? 

What is the best PDF file version that should be used ? Obviously I want to use the one with the least feature/bloat and most security I find acceptable... but the damned thing has to load my PDF's...

There's an error loading my PDF's, but no error code to work off of.  Is there a PDF.js tester I can upload my PDF's too ?

Any help would be much appreciated.

Thanks

![opera loading print pdf 1](https://f.cloud.github.com/assets/4941545/749965/abf347ae-e4ba-11e2-9511-bbd594d09e92.png)

![opera loading print pdf 2 error - no error message](https://f.cloud.github.com/assets/4941545/749964/abbdbeea-e4ba-11e2-8873-c3c0b8559068.png)

**Comment by miketaylr** [comment]
Hi there @5953lc. Are you able to attach or link to a failing PDF?

**Comment by 5953lc** [comment]
Ok. So what version of PDF does pdf.js support 100% ?  v1.3  v1.4  v1.5

Are there any ways to speed up PDF viewing, like changing the resolution,
color bits, page size ?   It takes 8 seconds to render the page from a
local network !!!

I am attaching a copy of a PDF that I can open up just fine with Mozilla
Firefox 22.0 / Mozilla Labs PDF.js Viewer 0.8.1 without any issue what so
ever.

But the same file I can't open up with Opera 15.0.1147.100 / Opera PDF.js
0.8.169 without it working.  Attached is a screen shot of the failure to
load - there is no error number at all ...

Thanks for answers to the above questions

Lyle

**Comment by Rob--W** [comment]
Works for me, using the PDF.js Opera extension v0.8.169 from the Opera Add-on gallery and Opera 15.0.1147.100.  
I've simulated a throttled + bandwidth-limited network, and although the PDF loads slower, it does show up. In either case, this is the rendered output:

![Opera, PDF.js + output_message.pdf](https://f.cloud.github.com/assets/1365071/756476/23a6a43c-e617-11e2-9ce8-bf09bee630ed.png)

**Comment by 5953lc** [comment]
So what would cause it not to render on my machine(s).  I've got 2 windows
8 pro machines where I can load Mozilla/PDF.js and that combo will work.
But when I load Opera 15 with PDF 8.169 or Opera NEXT with PDF 8.169 I get
an error message ?

How do I even figure out where the issue is ?

What version of PDF does pdf.js support 100% ?  Any PDF version above v 1.1
?    v1.3  v1.4  v1.5

Are there any ways to speed up PDF viewing, like changing the resolution,
color bits, page size ?

**Comment by 5953lc** [comment]
Oh. Windows 8 Pro in Desktop Mode.

**Comment by Rob--W** [comment]
@5953lc I tested and the viewer appears to work as intended for the file you've provided, on Windows 8. I don't know the answer to the question about "100% supported features", because I'm mainly working on the Chrome extension, not the PDF parser/renderer.

The PDF files referenced at test/pdfs/ range from version 1.0 to 1.6. To get an idea of what's being tested, I ran `file *test/pdfs/.pdf |grep -oP 'version [0-9.]+' |sort -n |uniq -c`, which yielded the following output (column 1 = number of pdf files, column 2 = PDF version):

```
  2 version 1.0
  3 version 1.1
  9 version 1.2
 28 version 1.3
 60 version 1.4
 18 version 1.5
 30 version 1.6
 13 version 1.7
```

Back to your issue
- Are you behind a proxy which mangles requests?
- If you change servers (e.g. a simple file server on localhost), does the error persist?
- If you start Opera with a new profile, does the error persist?
- Does the error also show up in the [Chrome extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm)?

**Comment by 5953lc** [comment]
No proxy.
problem still exists in if I change computers (same server) - even if it's
a brand new windows 8 pro and I load opera for the 1st time with the pdf.js
extension.
if I use mozilla & it's pdf.js extension it works fine.

the ERROR shows up in chrome with PDF.js versions 3.0.3 !!!!

Lyle

**Comment by 5953lc** [comment]
Here's some more information:

Opera Next 15.0.1147.100

PDF.js v0.8.169 (build: 869b878)

Message: Unexpected server response (500) while retrieving PDF "https://waldo.rssllc.us/RSS/agents/print_message".

Note: user tried to load a first call PDF at 1632

Here is what the browser is sending to the web server:

POST /RSS/agents/print_message HTTP/1.1>Host: waldo.rssllc.us
Connection: keep-alive
Content-Length: 20
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Origin: https://waldo.rssllc.us
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1
Content-Type: application/x-www-form-urlencoded
DNT: 1
Referer: https://waldo.rssllc.us/RSS/agents/message_form?msg_id=X26
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Cookie: SID=108.89.75.237:ejhA1DSFgxweI6uIEl

Does this shed light on the issue ?

**Comment by 5953lc** [comment]
Sorry - accidently closed the issue.

I am still having this issue. Please let me know what other information you may need to resolve this issue.

**Comment by 5953lc** [comment]
waiting for bug to be fixed.
