### ISSUE TITLE
Button for Rotate View Function

### ISSUE THREAD

**Issue by hennryns** [operasoftware/pdf.js#4]
Dear Sir / Madam,

I have question about Rotate View Function, although Rotate View Function can be done by pressing "r" or "Shift + r"; but is it possible for you to add standalone button for Rotate View Function on the toolbar?

Thank you.

**Comment by Snuffleupagus** [comment]
This will be solved upstream if/when https://github.com/mozilla/pdf.js/pull/2792 is merged.

**Comment by hennryns** [comment]
Dear All,

Thank you for the explanation.

Hopefully, someone from @operasoftware will update this extension to the latest version with [Secondary Toolbar](https://github.com/mozilla/pdf.js/pull/2792) capability immediately; so the user can get maximum benefits from this extension.

Thank you.

**Comment by timvandermeij** [comment]
Upstream PR #2792 has been merged, so it's all up to @operasoftware now to update the extension :)

**Comment by hennryns** [comment]
Dear @ppodgorski @operasoftware 

Kindly, please update the Opera PDF.js extension according the information from @timvandermeij immediately.

Thank you.

**Comment by ghost** [comment]
Extension update. Available this week on addons portal.
