### ISSUE TITLE
Error on Opening Local PDF File

### ISSUE THREAD

**Issue by hennryns** [operasoftware/pdf.js#5]
Dear Sir / Madam,

I understand this PDF JS Viewer has capability to open PDF File that stored on local disk; I managed to do this by using "Open File" button on the toolbar.

But it always shows error if I try to open the PDF File by dragging local PDF file and drop to the browser page. There is message: An error occurred while loading the PDF.

Do you have any advice on this issue?

Thank you.

PDF.js v0.8.169 (build: 869b878)

**Comment by Rob--W** [comment]
Did you put a tick at "Allow access to file URLs" at the extension settings page? If yes, does it also happen with the [Chrome extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) in Chrome?

**Comment by hennryns** [comment]
Yes, I already put a tick at "Allow access to file URLs" at the extension settings page on Opera 15; but error still happens.

Surprisingly, the error does not happen in [Chrome extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) in Chrome Browser; I also try to install the [Chrome extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) to Opera 15, and the error does not happen.

So, I think the problem is from this old [Opera PDF Viewer extension](https://addons.opera.com/en/extensions/details/pdf-viewer/?display=en); hopefully, someone from @operasoftware will update this extension to the latest version immediately.

Thank you.

**Comment by ghost** [comment]
Extension updated. This week available on addons portal.
