### ISSUE TITLE
error on loading pdf

### ISSUE THREAD

**Issue by unrealmirakulix** [operasoftware/pdf.js#6]
this file cannot be opened with the extension but works fine when opened in external PDF-Viewer (here: Sumatra PDF)

http://www.berlin.de/imperia/md/content/lb-patienten/patientenforum/martus_gute_studie.pdf?start&ts=1309357143&file=martus_gute_studie.pdf

another pdf only gives me blank page in extension:

http://imsieweb.uni-koeln.de/lehre/blockstat/MedStat13-KlinischeStudien.pdf

**Comment by Rob--W** [comment]
Thanks for reporting, I've fixed it via https://github.com/mozilla/pdf.js/pull/3516.
