### ISSUE TITLE
Who is maintaining the Opera extension?

### ISSUE THREAD

**Issue by Rob--W** [operasoftware/pdf.js#7]
The PDF Viewer has received several updates and improvements, but the entry in the Add-on gallery is still over a month old.

Can you sync the addon with the latest version? If you're short on personnel to handle this, I volunteer to take this task, as I'm already the maintainer of the Chrome extension.

To update the extension, follow the following steps:

```
git remote add upstream https://github.com/mozilla/pdf.js.git
git checkout master
git merge upstream master
node make generic chrome
cd build/extensions/chrome
zip ../chrome.zip *
# Upload to addons.opera.com, await review and done!
# Update remote repository
git push origin master
```

**Comment by 5953lc** [comment]
Is there any way to update the extension in the opera browser itself ? Opera is still stuck on the Version
0.8.169 from June 21, 2013.  Obviously it's not a priority for opera, but it's a priority for me.

**Comment by hennryns** [comment]
Yes, the new Opera Extensions have very similar structure to Chrome Extension.

You can try to install and use [this extension](https://addons.opera.com/en/extensions/details/download-chrome-extension-9/?display=en) and download [PDF Viewer Extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) from Chrome Web Store.

Hopefully, @operasoftware would take the help from @Rob--W to maintain the Opera PDF Viewer Extension.

Thank you.

**Comment by ghost** [comment]
Hi guys,

the newest version of PDF Viewer extension is already available on addons portal: https://addons.opera.com/en/extensions/details/pdf-viewer/?display=en

It's based on latest pdf.js lib.

**Comment by Rob--W** [comment]
@ppodgorski There's a bug in the current version of the viewer, include this patch to allow users to view local PDF files: https://github.com/Rob--W/pdf.js/commit/a4dd4b17893be9c672721329fc4b9ff57ea0c1cc (the bug has gone unnoticed for a while, so local files are rarely viewed in Chrome. Regardless, it needs to be fixed)

I usually merge Chrome-specific bug fixes before they are merged with the master branch of PDF.js, you can see which commits are live in the Chrome extension at https://github.com/Rob--W/pdf.js/commits/cws-release.

**Comment by ghost** [comment]
@Rob--W Thank you for pointing this. We will include this code and release new version.

**Comment by 5953lc** [comment]
I'd suggest closing this because it looks like Opera is looking at this and working with Rob.

Go Team!

:-)

When is the new version coming out Rob ?

**Comment by hennryns** [comment]
Dear @5953lc @ppodgorski 

I still do not think if @operasoftware is already working with @Rob--W on this PDF.js extension.

The release of Opera PDF.js is still behind the release of Chrome PDF.js and Firefox PDF.js; @operasoftware has not updated this extension since weeks. This leaves the Opera users with less features and bug fixes of new release, and this is very annoying.

Again, I would like to suggest @operasoftware to take the help from @Rob--W to maintain the Opera PDF.js; so the Opera users can get the release update sooner.

Thank you.

**Comment by ghost** [comment]
Dear @hennryns,

thanks for making a valuable point on PDF Viewer extension. We are on it and working on updating our extension to latest version of pdf.js lib. Sorry for delay with updates but we are switching between tasks as fast as possible.

Best regards,
Piotr

**Comment by 5953lc** [comment]
Thanks Piotr

I noticed that Opera PDF viewrer and Rob's Chrome Extension are now at the save version, but they are radically different sizes  Opera's 1.4M versus Chrome's 623KB.  

What's hiding in Opera's extension ?  A baby extension ?

By the way, PDF files generated via a form (POST request) CANNOT be viewed.  Still!....   ONLY the GET method works.

Opera needs to get that chrome.streamsPrivate API into the Opera browser or the Opera pdf.js PDF Viewer addon, 

Then the Opera/pdf viewer combo will work perfectly 100% of the time with any PDF/browser reception method GET or POST. 

Lyle

**Comment by ghost** [comment]
Dear Lyle,

you're welcome :)

We are working hard to get more and more extensions API enabled in our browser. Please stay tune, we will have some new options soon :)

Best regards,
Piotr

**Comment by Rob--W** [comment]
@5953lc
Opera has inserted a 1MB PDF file in the extension, probably by accident or intentional as a demo. It's the same PDF file that's used by PDF.js to preview the PDF Viewer at http://mozilla.github.io/pdf.js/, namely http://cdn.mozilla.net/pdfjs/tracemonkey.pdf.

You can use the [Chrome extension source viewer](https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin) to see what's inside a Chrome or Opera extension with a single click (visit the options page to enable support for Opera extensions). I've only hosted it in the Chrome Web store, but if there's demand for it, I can also submit it to Opera's add-on gallery.

**Comment by 5953lc** [comment]
Thanks for pointing that out.  It was a bit disconcerting ....   (And they
still don't have the POST issue fixed ... or the streamsPrivate API ...)

(sigh)

Back to firefox/pdf.js combo until they do...

**Comment by andreasbovens** [comment]
@Rob--W I've filed https://github.com/operasoftware/pdf.js/issues/9 to fix the PDF file issue. Sorry about that.

As for the Chrome extension source viewer extension, can you submit it to the Opera extensions catalog? We'd be happy to feature it.

**Comment by Rob--W** [comment]
@andreasbovens Submitted as https://addons.opera.com/extensions/details/extension-source-viewer/.
