### ISSUE TITLE
button to receive PDF via the POST method doesn't work (the GET method does)

### ISSUE THREAD

**Issue by 5953lc** [operasoftware/pdf.js#8]
All I have is a button on the website to click on in order to then receive the PDF from the website. (There is no download link) get the PDF.  Opera doesn't display the PDF, but rather downloads the PDF (instead of displaying it like Firefox/PDF.js does).

According to Rob W, look at the bottom of:  
https://github.com/mozilla/pdf.js/issues/3600

Is this the POST issue ?, which requires streamsPrivate API in order to fix.

**Comment by 5953lc** [comment]
I load the latest Firefox which includes the latest pdf.js code, and Firefox/pdf.js works with BOTH the GET method for getting PDF's from the website to the browser and then viewing them in the browser **AND** the POST method for getting PDF's from the website to the browser and then viewing them in the browser.

Then I loaded Opera's latest PDF viewer add-on v0.8.428 based on some version of the pdf.js code version unknown, and Opera/pdf.js combo WILL NOT WORK if the web site serving the PDF's uses the POST method to send the PDF files from the website to the browser - the Opera/pdf.js combo only works with the GET method ! So anytime the POST method is used it fails (without even an error codes/message)!

I've tested Rob's Chrome PDF.js https://chrome.google.com/webstore/support/oemmndcbldboiebfnladdacbdfmadadm?hl=en&gl=US#bug latest version 0.8.488 within the latest Opera, and we have determined that if Opera includes the chrome.streamsPrivate API into the Opera browser or the Opera pdf.js PDF Viewer addon, then the Opera/pdf.js combo will work perfectly 100% of the time with any POST method. Rob said that there would be performance and other enchancements available with the API as well.

Having the Opera browser include 100% compatibility with both methods of receiving PDF files from a website, whether it's the GET method or the POST method is a no-brainer based on the fact that it will save Opera time/money/programming resources that can be used elsewhere.

**Comment by 5953lc** [comment]
latest version of Opera 17 and 18 and latest version of Opera PDF Viewer 0.8.558 still can't get PDF files generated via a form (POST request) still CANNOT be viewed. ONLY the GET method works.

Opera needs to get that chrome.streamsPrivate API into the Opera browser or the Opera pdf.js PDF Viewer addon, 

Then the Opera/pdf viewer combo will work perfectly 100% of the time with any PDF/browser reception method GET or POST. 

Lyle

PS I noticed that Opera PDF viewer and the Chrome Extension PDF Viewer are now at the same exact version 0.8.558, but they are radically different sizes Opera's 1.4M versus Chrome's 623KB. 

What's hiding in Opera's extension ? A baby extension ?

**Comment by ghost** [comment]
Dear Lyle,

you're welcome :)

We are working hard to get more and more extensions API enabled in our browser. Please stay tune, we will have some new options soon :)

Best regards,
Piotr

**Comment by 5953lc** [comment]
Piotr

Thank you for the news. (and for putting the latest version of the pdf.js
add-on on the website)  The newer version have bugfixes, etc, but not the
one that I need regarding the only API  I'm interested in is the streamsPrivate
API I've mentioned.  It's the only one that will fix the POST method of
getting PDF's from websites and viewing them properly.

**Comment by ghost** [comment]
Dear Lyle,

we are doing our best to satisfy all our users with the best Internet and product experience. Incorporating new extensions APIs in the browser is one of our goals and we are working hard to deliver more and more with every release... but as everything, it requires time to provide each functionality with proper quality level... so please, be patient.

Best regards,
Piotr

**Comment by 5953lc** [comment]
:-)   I know I need to be patient.  But Rob Wu and I have already
determined a working solution (that missing API) and that we can work out
the details without involving opera staff, so they can move forward on
their stuff.  But adding that privatestreams API is taking forever....

By the way, does opera try to use available plugin's first (like adobe
acrobat reader), and then try any available extensions (opera's pdf.js pdf
viewer) next ?

**Comment by ghost** [comment]
We are global company and have to follow established product development processes, so streaming API need to wait for its turn :)

**Comment by 5953lc** [comment]
I understand - I've used Opera since year 1.  My issue is that I have
Chrome with built in PDF viewer and Firefox with built in viewer, and Opera
..... which doesn't have one that works.
Opera:
Privacy check
Security check
HTML5 check
PDF viewing PDF via GET  check
PDF viewing PDF via POST FAIL

PDF viewer capability is too ubiquitous to ignore, and Adobe's software is
too massive to continue to allow to exist.

**Comment by ghost** [comment]
Please believe me we are not ignoring PDF files support in Opera. Just be patient :)

**Comment by 5953lc** [comment]
Thanks. Please believe me, I wouldn't bitch about this PDF functionality if
it wasn't a huge huge problem for me.  We are using Chrome and Firefox but
they have horrible working issues for us.

Chrome is huge, bloated, javascript is fast, but could be much faster (why
can't javascript be run off the GPU?) , their built in PDF viewer is slow
and kludgy and their privacy/security is non-existant  .... and has the
best compatibility with our browser application but there's still that take
it or leave it attitude....

Firefox is less bloated, their javascript is damned fast (always could be
faster), their PDF viewer rocks (with GET AND POST methods), and they're
better about privacy and security... however their implementation of some
other things wrecks havoc with our browser applications ....

Opera 17 works great except for the PDF POST issue.  Opera 18 works too,
but there's no about:gpu information yet.  We would love to use those
wasted GPU cycles!!!!

Thanks

**Comment by 5953lc** [comment]
I loaded Opera's latest PDF viewer add-on Version 0.8.607.0 Last update Oct. 15, 2013 based on some version of the pdf.js code version unknown, and Opera/pdf.js combo WILL NOT WORK if the web site serving the PDF's uses the POST method to send the PDF files from the website to the browser - the Opera/pdf.js combo only works with the GET method ! So anytime the POST method is used it fails (without even an error codes/message)!

I've tested Rob's Chrome PDF.js ttps://chrome.google.com/webstore/support/oemmndcbldboiebfnladdacbdfmadadm?hl=en&gl=US#bug latest Version: 0.8.616 Updated: October 16, 2013 within the latest Opera, and we have determined that IF AND WHEN Opera includes the chrome.streamsPrivate API into the Opera browser or the Opera pdf.js PDF Viewer addon, then the Opera/pdf.js combo will work perfectly 100% of the time with any POST method. Rob said that there would be performance and other enchancements available with the API as well.

Opera has been updating their pdf.js browser much more regularly, which is awesome.  However Rob W has been updating his even faster, and we're both waiting for the chrome.streamsPrivate API to be put into the Opera browser!

Does anybody have any news or updates ? 

PLEASE!

thanks

**Comment by ghost** [comment]
@5953lc We are currently working on streamsPrivate API. It should be available hopefully soon, in one of the next versions of Opera browser. Please stay tuned.

**Comment by 5953lc** [comment]
That is wonderful news.  Are you working with  Andreas Bovens on this or
Rob Wu on this  ?

Does it look like it will be possible to have this in the next Opera
Developer 19 ?

Thanks.  I can't WAIT!!!! :-)

lyle

**Comment by 5953lc** [comment]
Is Zork the "owner" of the streamsPrivate API - https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/streams/OWNERS&q=zork

And when is this going to get completed ?

**Comment by Rob--W** [comment]
`streamsPrivate` is now upstream. When Opera pulls in the latest version of PDF.js, Opera 19+ users will benefit from the new APIs.

**Comment by 5953lc** [comment]
This issue has been fixed!!!!
