### ISSUE TITLE
Remove test PDF file from extension

### ISSUE THREAD

**Issue by andreasbovens** [operasoftware/pdf.js#9]
As pointed out by @Rob-ww on https://github.com/operasoftware/pdf.js/issues/7#issuecomment-25481098 , we're currently shipping a test PDF file inside the pdf.js extension in 0.8.558 on the extensions catalog.

This should be fixed.

**Comment by Rob--W** [comment]
What steps are you using to create the .nex file at the moment? Perhaps I can help you with creating a build script that automatically generates the nex file. I've created several of such tools for use in personal and business projects.
